### PR TITLE
Enable preamle templates

### PR DESCRIPTION
**Pull request by JensAc**
What do you think about this?

- A preamble template is supported
- The design is compatible to QTikZ
- A major benefit is that you can simply write the tikzpicture in a buffer, save it to a file and source it via `\input{.}` in your LaTeX document.

### CODE REVIEW

**Comment by emiliotorres** [comment]
Thank you very much for your kindly improvement!

Now, it really remembers QTikZ, that was the original inspiration.

**Comment by JensAc** [comment]
You're welcome! 
Would it be possible that you publish the current version on melpa, so that I can simply install it from there?

**Comment by emiliotorres** [comment]
You are right! 
But I am not sure how to do it. 

Is it just 
In  *emiliotorres/melpa*, select *Pull request*. Then select *New Pull request*  and
base repository: melpa/melpa master <- head repository: emiliotorres/mepla master
and *Create pull request*.

I am not sure if this pull automatically updates the emiliotorres/tikz (This is the link
*(tikz :repo "emiliotorres/tikz" :fetcher github)* And I do not find any instructions for dummies!

Are you so kindly as to provide me any suggestions on how to do it? Thank you!

**Comment by JensAc** [comment]
Actually, I just checked what I would get, if I installed from melpa and it is your latest commit. 
Therefore, everything is fine and users can install directly from melpa. 
Thanks very much!

**Comment by JensAc** [comment]
Update: I was a little too fast. I was able to install it, however the templates folder was not installed alongside `tikz.el`. I did not do any packaging for melpa so far. Maybe you could check, whether you could include that folder? Otherwise the default value of `tikz-preamble-template` points to nowhere.

**Comment by emiliotorres** [comment]
Ok. I don't remember very well about MELPA.

[Here](https://github.com/melpa/melpa#example-multiple-files-in-multiple-directories), an example shows something like this
```
package-YYYYMMDD
|-- snippets
|   |-- html-mode
|   |   |-- div
|   |   `-- html
|   `-- python-mode
|       |-- for
|       `-- main
`-- package.el 
```


So I guess I must modify  the tikz file in emiliotorres/melpa/recipes to
`(tikz 
:repo "emiliotorres/tikz" 
:fetcher github 
:files ("templates/*.el" "templates")) `
and request a pull to melpa/melpa.

I will try carefully, because I am very dull with control versions.

Just a silly question. This version will use the default templates. But if you want to modify it or use another one, how is the procedure?

**Comment by JensAc** [comment]
The template can be configured by setting the `tikz-preamble-template` variable. Sorry, I forgot to document that in the README. Maybe we should add that.

**Comment by emiliotorres** [comment]
I have questioned [in Stackoverflow](https://stackoverflow.com/questions/69347027/building-a-package-gives-single-file-templates-does-not-match-package-name) how to proceed. I have no idea!

**Comment by emiliotorres** [comment]
Ok. I think that the correct recipe is 
```
(tikz :repo "emiliotorres/tikz" :fetcher github
	  :files ("*.el" "templates"))
```
I have updated my melpa repository and asked a pull request to Melpa. Now it is under revision.

**Comment by JensAc** [comment]
I performed an update a second ago, and the templates directory does not appear to be installed alongside `tikz.el`. 
I found the `evil-collection` package installing a modes directory.
You can find the recipe [here](https://github.com/melpa/melpa/blob/master/recipes/evil-collection). Maybe that helps?

**Comment by JensAc** [comment]
Any updates on this? Of course, one the ` tikz-preamble-template` could be set to something meaningful in `init.el`. However, for newbies it would be great if just calling `tikz-mode` would result in an output directly.

**Comment by emiliotorres** [comment]
I think that it is updated by now:
https://github.com/melpa/melpa/pull/7738

Please, it would very nice if you provide a new version with your suggestions.  

I do not know very well how to git this changes. So I trust on you how to include changes.

**Comment by JensAc** [comment]
I think it is fine for now. I installed it once again from melpa and it works as expected.

**Pull request merged**
